# .github/workflows/deploy.yml
name: Deploy to VPS Server

on:
  push:
    branches:
      - master  # Запускати деплой при пуші в гілку master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Отримати код з репозиторію GitHub
      - name: Checkout code 📥
        uses: actions/checkout@v4

      #  Виконати збірку, якщо це необхідно (наприклад, для фронтенду)
      # - name: Build Project
      #   run: npm install && npm run build

      # 2. Визначення змінної версії
      # Використовуємо короткий хеш коміту як тег версії
      - name: Set Image Tag
        id: set_tag
        run: echo "IMAGE_TAG=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      # 3. Деплой через SSH
      - name: Deploy via SSH 🚀
        uses: appleboy/ssh-action@v1.0.3 # Популярний action для SSH
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: IMAGE_TAG
          script: |
            # 1. Перейти до робочої директорії на сервері
            cd /home/tomkat/docker_img/myResume/
            
            # 2. Оновити код з GitHub
            # Якщо ви вже один раз зробили git clone на сервері:
            #git pull origin master
            git pull
            echo "Current Image Tag is: $IMAGE_TAG"

            # 3. Додаткові команди після оновлення:
            sudo bash ./build.sh $IMAGE_TAG
            sudo bash ./run.sh $IMAGE_TAG
